### ISSUE TITLE
pytest-keyring is broken if using pytest > 8.0.2

### ISSUE THREAD

**Issue by vx-i** [tomasfarias/pytest-keyring#1]
If I use latest pytest version with pytest-keyring, I get an error message that FixtureDef has no argument fixturemanager:

FixtureDef.__init__() got an unexpected keyword argument 'fixturemanager'

This change was done by [this commit](https://github.com/pytest-dev/pytest/commit/372c17e22899e8e676e105dae714e897426bef86).

Workaround: pip install pytest==8.0.2

**Comment by tomasfarias** [comment]
Thanks for opening this issue and pointing to the breaking commit!

I can't really find the breaking change in the pytest docs. However, I updated the code to use `config` instead of `fituremanager` when creating a `FixtureDef` and the tests are passing. So, I'll release a new version `pytest-keyring` requiring pytest>8.0.2 with the code change.

**Comment by tomasfarias** [comment]
Version 1.0.4 has just been published to PyPI with this fix. Thanks once again!
